### ISSUE TITLE
Fingerprinting

### ISSUE THREAD

**Issue by martinthomson** [privacycg/gpc-spec#36]
This adds at most one bit of information to the fingerprinting surface of browsers[^1].  That probably won't be an issue, but the specification can at least acknowledge that point.

[^1]: It's not one bit exactly as the split between enabled and disabled (including no choice) is not perfectly even.  And arguably this situation gets better with more adoption.  As GPC on is more common, the surprisal or information gain that comes from learning that someone has enabled GPC is much lower.  Also, those who have not enabled GPC are increasingly the ones who have chosen to convey more information toward sites as opposed to those people who are unaware of the option or haven't yet decided.

**Comment by SebastianZimmeck** [comment]
@pes10k [further revised the language](https://github.com/globalprivacycontrol/gpc-spec/pull/41#pullrequestreview-1210618600).

**Comment by AramZS** [comment]
@martinthomson The changes we now have merged in were agreed upon as potentially needing additional text beyond what is there. Would you like to suggest something that would improve clarity or close this issue?

**Comment by martinthomson** [comment]
I'm still unhappy with the "we tried not to make it worse, really" implications of that last statement.

Why not just say something like:

> Exposing a user's preference (in the HTTP header field or `navigator` object[^1]) potentially divides users into two groups in a way that might increase the information available for fingerprinting.  This extra information is available unless the signal perfectly correlates with other signals [^3]. This represents a privacy cost that is justified[^2] by the privacy advantage provided by sending the signal. 

[^1]: Note that the formatting in the draft is [a little off](https://privacycg.github.io/gpc-spec/#privacy).
[^3]: I wouldn't say this, but a decision to enable always would mean that the users of that browser don't contribute any signal beyond what the user agent identification would.
[^2]: I don't know how to do this without the passive voice; I wanted to say "we believe it to be justified", but "we" is super ambiguous, which I don't like.

**Comment by pes10k** [comment]
FWIW, I'm mostly fine with @martinthomson 's suggested text, with the following change:

Change:

> This represents a privacy cost that is justified by the privacy advantage provided by sending the signal.

to

> Depending on the browser and implementation, the GPC signal may impose a privacy cost, though one intended to be justified by the privacy advantage provided by sending the signal.

I think this change is important bc the previous sentence recognizes that in some deployments the GPC signal doesn't provide additional fingerprinting-signal. My suggestion aims to just carry that recognition into the next sentence.

If that all sounds good / no one opposes it, i'll update the PR and merge
