### ISSUE TITLE
Legal Effects section may fall out of date

### ISSUE THREAD

**Issue by bvandersloot-mozilla** [privacycg/gpc-spec#53]
Is there any way to ensure the relevant legal effects remain up to date? I would like to avoid stagnation of this section in particular, which is meant to reflect a non-technical description of the world's legal landscape. I have a lot of blind spots when it comes to consumer data protection laws, and the current list includes no reference to laws outside of the USA and Europe. I know a lot of countries have GDPR-like laws and opt-out clauses, so it may be the case that the current text has some blind spots as well.

**Comment by jyasskin** [comment]
Could we do this section as a [Registry](https://www.w3.org/2023/Process-20230612/#registries) so it can be updated outside the WG process? This would be an unexpected use for registries, but it seems to mostly fit. I think the biggest challenge would be defining how the custodian should figure out whether a proposed entry is legally correct.

**Comment by j-br0** [comment]
We could alternatively create a separate explainer document for implementers as @AramZS proposed in Issue #56. I don't have a strong feeling about whether an explainer or a registry makes sense, but it probably does make sense for details about various and evolving legal guidance to be in a separate document outside of the spec itself.

Either way, we should stay away from too much normative interpretation of different jurisdictions' legal requirements and stick to just trying to accurately capture the relevant text of statutes, regulations, or other policy statements from legislators and regulators.

**Comment by AramZS** [comment]
We think that maintaining these explanations in the explainer is for the best. @bvandersloot-mozilla - is the current text satisfactory in covering your concerns?

**Comment by npdoty** [comment]
It seems like a Registry is where you want a W3C-defined process to be the deciding factor in how something is applied. But in this case, what is being discussed is documenting decisions that are made elsewhere (in government bodies, primarily). 

Could the spec briefly and non-normatively summarize legal effects and provide an informative reference to a documentation page that could be kept up to date? A w3c wiki page or MDN, say. Or +1 to using an explainer for that purpose for now.

**Comment by bvandersloot-mozilla** [comment]
The current text is satisfactory for me!
