### ISSUE TITLE
Set up explainer document in this repo with more detail for implementers 

### ISSUE THREAD

**Issue by AramZS** [privacycg/gpc-spec#56]

**Comment by martinthomson** [comment]
@SebastianZimmeck, is there a specific question that the group can help you with here?  Also, how much time do you expect that discussion to take?  I think that we can find time for this at the meeting this week, but I need a little help with scheduling.

**Comment by SebastianZimmeck** [comment]
Here is the [explainer](https://docs.google.com/document/d/14e7iWqm2zmyEShNq5yGXVrnYQC5BVBMhnNrMRtpOmwM/edit?pli=1). 

@martinthomson, the question is what, if anything, should be changed in the explainer to make it most helpful to implementers (e.g., publishers, browser vendors)?

I think 15 minutes would be a good amount of time to reserve.

**Comment by annevk** [comment]
Some feedback:

* The header needs to be a structured header. We should not add new non-structured headers to the web platform. (I have given this feedback a number of times.)
* The new member of `Navigator` should always be present and return false when the signal is not present. Conditional members are generally not supported by Web IDL and also bad for a number of optimizations around object shapes and such.

**Comment by bvandersloot-mozilla** [comment]
> The new member of Navigator should always be present and return false when the signal is not present. Conditional members are generally not supported by Web IDL and also bad for a number of optimizations around object shapes and such.

The spec defines it as always present, and false if the user hadn't expressed a do-not-sell-or-share preference at the time of navigation. The spec is reasonable imo.

**Comment by SebastianZimmeck** [comment]
As discussed in [today's PrivacyCG meeting](https://docs.google.com/document/d/1DZEhS1UHJ1PKxt5ZwKmn5LZ4bo10UFyNXeLp2dUuzRM/edit#heading=h.9a4smtitowo2), please feel free to add your suggestions to the [Explainer](https://docs.google.com/document/d/14e7iWqm2zmyEShNq5yGXVrnYQC5BVBMhnNrMRtpOmwM/edit?usp=sharing) within the next two weeks. At that point, we will convert the Explainer format to markdown and open a PR here.

**Comment by SebastianZimmeck** [comment]
The explainer is now merged into main.

> The header needs to be a structured header. 

This point is discussed in #6.

> The spec defines it as always present, and false if the user hadn't expressed a do-not-sell-or-share preference at the time of navigation. The spec is reasonable imo.

Agreed.
