### ISSUE TITLE
Mixed documentation on navigator.globalPrivacyControl returning 1 or true

### ISSUE THREAD

**Issue by ryan-a-guthrie** [privacycg/gpc-spec#64]
This is particularly a problem with Typescript or any JS code using proper validation instead of 'truthiness' 

navigator.globalPrivacyControl

Chrome returns 1
https://global-privacy-control.glitch.me/  says it should return 1
https://privacycg.github.io/gpc-spec/#javascript-property-to-detect-preference - says it should be a boolean
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/globalPrivacyControl - says it should return true

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/globalPrivacyControl also indicates it isn't supported anywhere except Firefox, which seems false. They are missing the specs as well so there seems a big gap

**Comment by AramZS** [comment]
I agree we should make sure this is clear in the explainer: the header on the HTTP request is `1` the `navigator` property is `true` and that is the expected behavior.

**Comment by ryan-a-guthrie** [comment]
Ah ok, I do have the GPC plugin from Protegis,  so that must be what is returning 1, so that would be a bug on their side according to the spec. I'm not clear if there is any overlap between this group and them, but I will send them an email.

**Comment by AramZS** [comment]
@ryan-a-guthrie Does the new text in the explainer changes in #61 explain this sufficiently clearly?

**Comment by SebastianZimmeck** [comment]
@ryan-a-guthrie, is this OK with you? If so, we we will close this issue. This resolves it for me.
