### ISSUE TITLE
GPC spec status

### ISSUE THREAD

**Issue by HeinzBaumann** [privacycg/gpc-spec#72]
I served across all the privacycg github repo but wasn't sure where to ask this question: I am just curious to learn where in the process the GPC proposal is. What time frame are we looking at when this will be a w3 standard. Thanks!

**Comment by SebastianZimmeck** [comment]
@HeinzBaumann, here is the [current timeline](https://www.w3.org/2023/12/proposed-wg-privacy.html) (section 3.4). Though, we are a bit delayed.

**Comment by HeinzBaumann** [comment]
@SebastianZimmeck Thank you for the link. Quick question: what does this actually mean? "February 2025: Global Privacy Control, Candidate Recommendation". Is this the data is goes into the w3 specification?

**Comment by SebastianZimmeck** [comment]
The [Candidate Recommendation](https://www.w3.org/2023/Process-20231103/#RecsCR) is just one particular step in the process.

**Comment by SebastianZimmeck** [comment]
@HeinzBaumann, if you have further questions, please feel free to reopen.
